### ISSUE TITLE
To upload MCA result

### ISSUE THREAD

**Issue by NatashaMalik-50** [Sid-2D/Outcome-IPU#7]
Since the parser works for ipu results of all courses, if the result for MCA course could also be added, that'd
 be of great help!

**Comment by nm240nm** [comment]
Thankyou. PFA the MCA result pdfs. ​
 044_MCA_2nd_Semester_2015_Batch_Final Result_Ma...
<https://drive.google.com/file/d/1qSxbRI691lG8mgWXfA3Hd5NTC7U_SRdX/view?usp=drive_web>
​​
 044_MCA_2015_Batch_Final_Result_Dec.2015.pdf
<https://drive.google.com/file/d/1LuZH44RlM1v9AtA_4D_3ffpALEPLlh4L/view?usp=drive_web>
​​
 044_MCA_2015_onwards_Batch_mj2017.pdf
<https://drive.google.com/file/d/1Hdswey630QO9DH4RFPT8N-E2Juqqr_H8/view?usp=drive_web>
​​
 2015_MCA_FINAL_result_december_2015.pdf
<https://drive.google.com/file/d/1EOSBLjQWKBFzGMUU70W3igatfuDJWgQU/view?usp=drive_web>
​​
 MCA-FINAL_result_2015 onwards dec2017.pdf
<https://drive.google.com/file/d/1nyIUCoDOCXK6DwNDHd8NRo8JUqzg5S6M/view?usp=drive_web>
​

**Comment by Sid-2D** [comment]
The above PDFs have been added. There were some parsing errors so few results are corrupted because of that but a good majority of the results are available just fine. All features should work for MCA too. Please take a look and let me know!

Also I need to add your name as a contributor for the MCA results along with a link to your repo on the main page of this repo, so it'll be nice if you share that otherwise I'll just add @nm240nm

**Comment by Sid-2D** [comment]
I have fixed yours manually for now and you can take a look again. Will surely fix all the others when I get the time. Your name and a link to your profile have been added under the contributors section of this repo. Thanks for the help!

**Comment by NatashaMalik-50** [comment]
Thank you so much!
